version: "3.8"

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root1234
    ports:
      - 1433:1433
      
  app:
    depends_on:
      - mssqldb
    build: ./testpulse-master
    restart: on-failure
    container_name: spring_app
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:sqlserver://mssqldb:1433;databaseName=testpulsedb;",
        "spring.datasource.username" : "sa",
        "spring.datasource.password" : "root1234"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


volumes:
  db: